export const GET_AUTH = 'GET_AUTH';
export const GET_MEMBER_LIST = 'GET_MEMBER_LIST';
export const GET_MEMBER_DUES = 'GET_MEMBER_DUES';
export const GET_MEMBER_DONATIONS = 'GET_MEMBER_DONATIONS';
export const CREATE_MEMBER_DONATION = 'CREATE_MEMBER_DONATION';
export const CREATE_MEMBER_DUE = 'CREATE_MEMBER_DUE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SIGN_UP = 'SIGN_UP';

export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';
export const GET_MEMBER_LIST_ERROR = 'GET_MEMBER_LIST_ERROR';
export const GET_MEMBER_DUES_ERROR = 'GET_MEMBER_DUES_ERROR';
export const GET_MEMBER_DONATIONS_ERROR = 'GET_MEMBER_DONATIONS_ERROR';
export const CREATE_MEMBER_DONATION_ERROR = 'CREATE_MEMBER_DONATION_ERROR';
export const CREATE_MEMBER_DUE_ERROR = 'CREATE_MEMBER_DUE_ERROR';
export const SET_USER_DATA_ERROR = 'SET_USER_DATA_ERROR';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
